ci: add ci-passed generic job

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -164,3 +164,24 @@ jobs:
         with:
           name: ${{ matrix.artifact }}
           path: dist
+
+  ci-passed:
+    name: CI Passed
+    runs-on: ubuntu-latest
+    if: always()
+    needs: [pre-commit, fmt, lint, audit, deny, test, coverage, build]
+    steps:
+      - name: Check status of all required jobs
+        run: |
+          echo "Results: ${{ toJson(needs) }}"
+          if [[ "${{ contains(needs.*.result, 'failure') }}" == "true" || "${{ contains(needs.*.result, 'cancelled') }}" == "true" ]]; then
+            echo "One or more jobs failed or were cancelled"
+            exit 1
+          fi
+
+          if [[ "${{ contains(needs.*.result, 'skipped') }}" == "true" ]]; then
+            echo "One or more jobs were skipped, but strictly required"
+            exit 1
+          fi
+
+          echo "All required checks passed"
